# Generated by Django 5.0 on 2025-08-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_vendor_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.CharField(choices=[('1', 'Customer'), ('2', 'Editor'), ('3', 'Vendor')], default='1', max_length=20),
        ),
    ]
