# Generated by Django 5.0 on 2025-08-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_is_vendor_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.AddField(
            model_name='customuser',
            name='vendor_type',
            field=models.CharField(blank=True, choices=[('vendor', 'Vendor'), ('reseller', 'Reseller'), ('shop', 'Shop')], max_length=20, null=True),
        ),
    ]
