# Generated by Django 5.0 on 2025-08-31 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendors', '0002_withdrawrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorstore',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
