# Generated by Django 5.0 on 2025-08-24 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_completedoderitems_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.industry'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categories'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categories'),
        ),
    ]
