# Generated by Django 5.0 on 2025-08-24 12:03

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_categories_industry_alter_product_categories_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.industry'),
        ),
        migrations.AlterField(
            model_name='cuponcodegenaration',
            name='up_to',
            field=models.PositiveIntegerField(help_text='Limit of Discount Amount'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='details_description',
            field=ckeditor.fields.RichTextField(help_text='Detailed product description displayed at the bottom of the product page. Helps buyers make a decision.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(help_text='Enter your tag comma separated', max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.categories'),
        ),
    ]
