# Generated by Django 5.0 on 2025-08-24 12:13

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_categories_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.industry'),
        ),
        migrations.AlterField(
            model_name='cuponcodegenaration',
            name='up_to',
            field=models.PositiveIntegerField(help_text='Limit of Discount Amaount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='details_description',
            field=ckeditor.fields.RichTextField(help_text="Details product description display in the bottom of the product Page. It's help buyer to make deceion on your product", max_length=5000),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(help_text='Enter your tag coma separated', max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.categories'),
        ),
    ]
