# Generated by Django 5.0 on 2025-08-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_categories_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_top_deal',
            field=models.BooleanField(default=False, help_text='Mark product as top deal'),
        ),
        migrations.AddField(
            model_name='product',
            name='top_deal_expiry',
            field=models.DateTimeField(blank=True, help_text='Expiry date for the top deal', null=True),
        ),
    ]
