# Generated by Django 5.0 on 2025-08-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_is_featured_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounted_parcent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
