# Generated by Django 5.0 on 2025-08-30 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='product',
        ),
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.categories'),
        ),
    ]
