# Generated by Django 5.0 on 2025-08-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_helpvideo_complain'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpvideo',
            name='slug',
            field=models.SlugField(default='default-video', unique=True),
        ),
    ]
