# Generated by Django 5.0 on 2025-08-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_resellproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='placedoder',
            name='payment_method',
            field=models.CharField(choices=[('bkash', 'Bkash'), ('nagad', 'Nagad'), ('cod', 'Cash On Delivery')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='placedoder',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
